version: '2'
services:
  scouting-db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=yeti_scouting
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=yeti_scouting
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - "80:80"
    environment:
      - PMA_HOST=scouting-db
      - PMA_USER=yeti_scouting
      - PMA_PASSWORD=password
    depends_on:
      - scouting-db